package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_sass//:defs.bzl", "sass_library")

sass_library(
    name = "layout",
    srcs = [
        "footer.sass",
        "hero.sass",
        "section.sass",
    ],
)