package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_sass//:defs.bzl", "sass_library")

sass_library(
    name = "utilities",
    srcs = [
        "animations.sass",
        "controls.sass",
        "derived-variables.sass",
        "extends.sass",
        "functions.sass",
        "initial-variables.sass",
        "mixins.sass"
    ],
)