package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_sass//:defs.bzl", "sass_library")

sass_library(
    name = "components",
    srcs = [
        "breadcrumb.sass",
        "card.sass",
        "dropdown.sass",
        "level.sass",
        "media.sass",
        "menu.sass",
        "message.sass",
        "modal.sass",
        "navbar.sass",
        "pagination.sass",
        "panel.sass",
        "tabs.sass"
    ],
)