package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_sass//:defs.bzl", "sass_library")

sass_library(
    name = "form",
    srcs = [
        "checkbox-radio.sass",
        "file.sass",
        "input-textarea.sass",
        "select.sass",
        "shared.sass",
        "tools.sass"
    ],
)