package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_sass//:defs.bzl", "sass_library")

sass_library(
    name = "base",
    srcs = [
        "animations.sass",
        "generic.sass",
        "helpers.sass",
        "minireset.sass"
    ],
)