package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_sass//:defs.bzl", "sass_library")

sass_library(
    name = "elements",
    srcs = [
        "box.sass",
        "button.sass",
        "container.sass",
        "form.sass",
        "content.sass",
        "icon.sass",
        "image.sass",
        "notification.sass",
        "other.sass",
        "progress.sass",
        "table.sass",
        "tag.sass",
        "title.sass"
    ],
)