package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_sass//:defs.bzl", "sass_library")

sass_library(
    name = "helpers",
    srcs = [
        "color.sass",
        "flexbox.sass",
        "float.sass",
        "other.sass",
        "overflow.sass",
        "position.sass",
        "spacing.sass",
        "typography.sass",
        "visibility.sass"
    ],
)